# Generated by Django 6.0.5 on 2026-06-15 16:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modello', models.CharField(max_length=100)),
                ('anno', models.IntegerField()),
                ('chilometraggio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('alimentazione', models.CharField(max_length=50)),
                ('cambio', models.CharField(max_length=50)),
                ('colore', models.CharField(max_length=50)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('tipo_auto', models.CharField(choices=[('nuova', 'Nuova'), ('usata', 'Usata')], max_length=20)),
                ('stato', models.CharField(choices=[('disponibile', 'Disponibile'), ('venduta', 'Venduta'), ('in_manutenzione', 'In manutenzione'), ('noleggiata', 'Noleggiata')], default='disponibile', max_length=20)),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auto',
            },
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('partita_iva', models.CharField(max_length=20, unique=True)),
                ('indirizzo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('indirizzo', models.CharField(max_length=200)),
                ('citta', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedi',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('ruolo', models.CharField(choices=[('cliente', 'Cliente'), ('venditore', 'Venditore'), ('meccanico', 'Meccanico')], max_length=20)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('stipendio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='Fornitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fornitura', models.DateField()),
                ('prezzo_acquisto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fornitura', to='garage.auto')),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forniture', to='garage.fornitore')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forniture', to='garage.sede')),
            ],
            options={
                'verbose_name': 'Fornitura',
                'verbose_name_plural': 'Forniture',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garage.sede'),
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_test_drive', models.DateField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive', to='garage.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_cliente', to='garage.utente')),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_drive_venditore', to='garage.utente')),
            ],
            options={
                'verbose_name': 'Test drive',
                'verbose_name_plural': 'Test drive',
            },
        ),
        migrations.CreateModel(
            name='Noleggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('costo_giornaliero', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('costo_totale', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noleggi', to='garage.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noleggi_cliente', to='garage.utente')),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noleggi_venditore', to='garage.utente')),
            ],
            options={
                'verbose_name': 'Noleggio',
                'verbose_name_plural': 'Noleggi',
            },
        ),
        migrations.CreateModel(
            name='Intervento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_intervento', models.DateField()),
                ('tipo_intervento', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventi', to='garage.auto')),
                ('meccanico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventi_meccanico', to='garage.utente')),
            ],
            options={
                'verbose_name': 'Intervento',
                'verbose_name_plural': 'Interventi',
            },
        ),
        migrations.CreateModel(
            name='Vendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vendita', models.DateField()),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendita', to='garage.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendite_cliente', to='garage.utente')),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendite_venditore', to='garage.utente')),
            ],
            options={
                'verbose_name': 'Vendita',
                'verbose_name_plural': 'Vendite',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commento', models.TextField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='garage.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_cliente', to='garage.utente')),
            ],
            options={
                'verbose_name': 'Recensione',
                'verbose_name_plural': 'Recensioni',
                'unique_together': {('cliente', 'auto')},
            },
        ),
        migrations.CreateModel(
            name='Impiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impieghi', to='garage.sede')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impieghi', to='garage.utente')),
            ],
            options={
                'verbose_name': 'Impiego',
                'verbose_name_plural': 'Impieghi',
                'unique_together': {('dipendente', 'sede')},
            },
        ),
    ]
