# Generated by Django 6.0.5 on 2026-06-15 14:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('partita_iva', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=200)),
                ('citta', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modello', models.CharField(max_length=100)),
                ('anno', models.IntegerField()),
                ('chilometraggio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('alimentazione', models.CharField(max_length=50)),
                ('cambio', models.CharField(max_length=50)),
                ('colore', models.CharField(max_length=50)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_auto', models.CharField(choices=[('nuova', 'Nuova'), ('usata', 'Usata')], max_length=20)),
                ('stato', models.CharField(choices=[('disponibile', 'Disponibile'), ('venduta', 'Venduta'), ('manutenzione', 'In manutenzione'), ('noleggiata', 'Noleggiata')], default='disponibile', max_length=20)),
                ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.fornitore')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('ruolo', models.CharField(choices=[('cliente', 'Cliente'), ('venditore', 'Venditore'), ('meccanico', 'Meccanico')], max_length=20)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Intervento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_intervento', models.DateField()),
                ('tipo_intervento', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.auto')),
                ('meccanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventi_meccanico', to='garage.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Vendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vendita', models.DateField()),
                ('prezzo_finale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garage.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendite_cliente', to='garage.utente')),
                ('venditore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendite_venditore', to='garage.utente')),
            ],
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_test_drive', models.DateField()),
                ('stato', models.CharField(choices=[('prenotato', 'Prenotato'), ('effettuato', 'Effettuato'), ('annullato', 'Annullato')], default='prenotato', max_length=20)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_cliente', to='garage.utente')),
                ('venditore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_drive_venditore', to='garage.utente')),
            ],
            options={
                'unique_together': {('cliente', 'auto')},
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commento', models.TextField(blank=True, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_cliente', to='garage.utente')),
            ],
            options={
                'unique_together': {('cliente', 'auto')},
            },
        ),
    ]
