# Generated by Django 6.0.5 on 2026-05-12 14:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modello', models.CharField(max_length=50)),
                ('anno_immatricolazione', models.PositiveIntegerField()),
                ('chilometraggio', models.PositiveIntegerField(default=0)),
                ('alimentazione', models.CharField(max_length=30)),
                ('cambio', models.CharField(max_length=30)),
                ('colore', models.CharField(max_length=30)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('tipo_auto', models.CharField(choices=[('nuova', 'Nuova'), ('usata', 'Usata')], max_length=20)),
                ('stato', models.CharField(choices=[('disponibile', 'Disponibile'), ('venduta', 'Venduta'), ('in_manutenzione', 'In manutenzione')], default='disponibile', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id_utente', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('utente', models.OneToOneField(db_column='id_utente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='garage.utente')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('codice_fiscale', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('utente', models.OneToOneField(db_column='id_utente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='garage.utente')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('ruolo', models.CharField(choices=[('venditore', 'Venditore'), ('meccanico', 'Meccanico')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendita',
            fields=[
                ('id_vendita', models.AutoField(primary_key=True, serialize=False)),
                ('data_vendita', models.DateField()),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garage.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.cliente')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.dipendente')),
            ],
        ),
        migrations.CreateModel(
            name='Intervento',
            fields=[
                ('id_intervento', models.AutoField(primary_key=True, serialize=False)),
                ('data_intervento', models.DateField()),
                ('tipo_intervento', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.auto')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.dipendente')),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id_recensione', models.AutoField(primary_key=True, serialize=False)),
                ('voto', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commento', models.TextField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.cliente')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cliente', 'auto'), name='unique_recensione_cliente_auto')],
            },
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id_test_drive', models.AutoField(primary_key=True, serialize=False)),
                ('data_test_drive', models.DateField()),
                ('stato', models.CharField(choices=[('prenotato', 'Prenotato'), ('effettuato', 'Effettuato'), ('annullato', 'Annullato')], default='prenotato', max_length=20)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.cliente')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.dipendente')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cliente', 'auto'), name='unique_testdrive_cliente_auto')],
            },
        ),
    ]
