# Generated by Django 6.0.5 on 2026-06-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'Auto', 'verbose_name_plural': 'Auto'},
        ),
        migrations.AlterModelOptions(
            name='fornitore',
            options={'verbose_name': 'Fornitore', 'verbose_name_plural': 'Fornitori'},
        ),
        migrations.AlterModelOptions(
            name='intervento',
            options={'verbose_name': 'Intervento', 'verbose_name_plural': 'Interventi'},
        ),
        migrations.AlterModelOptions(
            name='recensione',
            options={'verbose_name': 'Recensione', 'verbose_name_plural': 'Recensioni'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name': 'Sede', 'verbose_name_plural': 'Sedi'},
        ),
        migrations.AlterModelOptions(
            name='testdrive',
            options={'verbose_name': 'Test drive', 'verbose_name_plural': 'Test drive'},
        ),
        migrations.AlterModelOptions(
            name='utente',
            options={'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
        migrations.AlterModelOptions(
            name='vendita',
            options={'verbose_name': 'Vendita', 'verbose_name_plural': 'Vendite'},
        ),
    ]
